AWSTemplateFormatVersion: '2010-09-09'
Description: status.yuriko.co.nz
Resources:
  AssetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: status.yuriko.co.nz
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
        BlockPublicAcls: false
        BlockPublicPolicy: false
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: awsApplication
          Value: !Sub arn:aws:resource-groups:${AWS::Region}:${AWS::AccountId}:group/Monitoring/05xiogayffmqq2ceul7z4fdmsv
      LifecycleConfiguration:
        TransitionDefaultMinimumObjectSize: all_storage_classes_128K
        Rules:
          - Status: Enabled
            Id: archive-non-current-version
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 30
            Prefix: ''
            NoncurrentVersionTransitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
              - StorageClass: ONEZONE_IA
                TransitionInDays: 60
              - StorageClass: DEEP_ARCHIVE
                TransitionInDays: 180
    DeletionPolicy: Retain
  IAMRoleStatusYurikoCoNzLambda:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    Properties:
      Path: "/service-role/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
      - "arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess"
      - !Sub arn:aws:iam::${AWS::AccountId}:policy/service-role/AWSLambdaBasicExecutionRole-ef255690-f70c-4404-967e-cdb8cf1a3636
      - "arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess"
      MaxSessionDuration: 3600
      RoleName: status-yuriko-co-nz-role-e8lm476y
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "lambda.amazonaws.com"
