AWSTemplateFormatVersion: '2010-09-09'
Description: status.yuriko.co.nz
Resources:
  AssetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: status.yuriko.co.nz
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
        BlockPublicAcls: false
        BlockPublicPolicy: false
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: awsApplication
          Value: !Sub arn:aws:resource-groups:${AWS::Region}:${AWS::AccountId}:group/Monitoring/05xiogayffmqq2ceul7z4fdmsv
      LifecycleConfiguration:
        TransitionDefaultMinimumObjectSize: all_storage_classes_128K
        Rules:
          - Status: Enabled
            Id: archive-non-current-version
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 30
            Prefix: ''
            NoncurrentVersionTransitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
              - StorageClass: ONEZONE_IA
                TransitionInDays: 60
              - StorageClass: DEEP_ARCHIVE
                TransitionInDays: 180
    DeletionPolicy: Retain
